### ISSUE TITLE
Gradio styling not respected

### ISSUE THREAD

**Issue by henryruhs** [freddyaboulton/gradio-range-slider#1]
Please respect the Gradio styles and reuse their classes.

![Screenshot from 2024-05-30 14-29-25](https://github.com/freddyaboulton/gradio-range-slider/assets/1835397/6b8055d8-a673-4d05-a5d4-fc0e9df4b501)

After our modifications at FF it looks worse, I only modify on a input=["range"] level:

![Screenshot from 2024-05-30 14-29-32](https://github.com/freddyaboulton/gradio-range-slider/assets/1835397/8e7e0fc0-26d3-4732-86ea-e8262c073861)

**Comment by freddyaboulton** [comment]
Are you using custom css? If so, can you share?

**Comment by henryruhs** [comment]
The first screen is without custom css, even there you can see that Gradio has different styles.

https://github.com/facefusion/facefusion/blob/feat/range-slider/facefusion/uis/assets/overrides.css#L14

That is also the branch that integrates your range slider. I did not spend time adjusting your styles. It's better to solve it on your side.

**Comment by freddyaboulton** [comment]
Ok it's actually a bug on gradio imo. I do not use firefox but I thought gradio's slider looked the same across browsers. So I added some css to make the range slider consistent across chrome and firefox. But looks like gradio does not apply consistent styles across browsers for the slider. 

So I removed my css so that it mirrors the core slider's behavior. Released in version 0.0.4

**Comment by henryruhs** [comment]
error remains... the approach of replicating / mirroring is not suitable. I fixed Gradio already, now I have to double-fix it!?

![image](https://github.com/freddyaboulton/gradio-range-slider/assets/1835397/ff3442da-46b6-43a8-b4ea-574a73418fb9)

**Comment by freddyaboulton** [comment]
I took a look and it is likely caused by the custom css in your app. I removed it and the range slider renders correctly.

<img width="561" alt="image" src="https://github.com/freddyaboulton/gradio-range-slider/assets/41651716/0020b3d2-8ccd-4884-90e8-df0f4842192e">

If these overrides must be applied, consider using `elem_classes` in the sliders already present so that your css only apply to those sliders. Style conflicts are expected if they are applied broadly like this.

**Comment by henryruhs** [comment]
We are not gonna use the slider when it needs additional fixes and does not follow the Gradio stylings.

I repeated multiple times that you should use Gradios styles rather than your own.

Giving up at this point. Thanks for your efforts.
